//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web08.QLTS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web08.QLTS.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input data.
        /// </summary>
        public static string DevMeg_ValidateFailed {
            get {
                return ResourceManager.GetString("DevMeg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch an exception.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error asset duplicate exception .
        /// </summary>
        public static string DevMsg_ValidateDuplicateCode {
            get {
                return ResourceManager.GetString("DevMsg_ValidateDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/e001.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteByID.
        /// </summary>
        public static string Proc_DeleteByID {
            get {
                return ResourceManager.GetString("Proc_DeleteByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Deletes.
        /// </summary>
        public static string Proc_Deletes {
            get {
                return ResourceManager.GetString("Proc_Deletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_EditByID.
        /// </summary>
        public static string Proc_EditByID {
            get {
                return ResourceManager.GetString("Proc_EditByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetAll.
        /// </summary>
        public static string Proc_GetAll {
            get {
                return ResourceManager.GetString("Proc_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetByAssetID.
        /// </summary>
        public static string Proc_GetByAssetID {
            get {
                return ResourceManager.GetString("Proc_GetByAssetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetMaxCode.
        /// </summary>
        public static string Proc_GetMaxCode {
            get {
                return ResourceManager.GetString("Proc_GetMaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetPaging.
        /// </summary>
        public static string Proc_GetPaging {
            get {
                return ResourceManager.GetString("Proc_GetPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_InsertOne.
        /// </summary>
        public static string Proc_InsertOne {
            get {
                return ResourceManager.GetString("Proc_InsertOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA.
        /// </summary>
        public static string UseMsg_Exception {
            get {
                return ResourceManager.GetString("UseMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản đã tồn tại.
        /// </summary>
        public static string UseMsg_ValidateDuplicateCode {
            get {
                return ResourceManager.GetString("UseMsg_ValidateDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("UserMsg_ValidateFailed", resourceCulture);
            }
        }
    }
}
